#!/bin/sh
#
# Gradle start up script for POSIX generated by Gradle.
# Placeholder — the real gradlew will be generated by Gradle wrapper.
# For CI, use `gradle wrapper` first or install Gradle directly.
